package oidcauth

import (
	"context"
	"errors"
	"time"
)

// ErrSessionNotFound is returned by SessionStore and SessionManager whenever
// a session cannot be resolved: it never existed, was already deleted, has
// expired, or failed to refresh. Callers should treat every case the same
// way (401 Unauthorized) rather than branching on the reason, since leaking
// which one applies is not useful to an unauthenticated caller.
var ErrSessionNotFound = errors.New("oidcauth: session not found")

// TokenSet holds every OIDC credential and lifetime fact a session needs to
// keep working without the browser ever seeing it: the tokens themselves,
// plus enough metadata to decide when to refresh and when the session's
// authorization from the identity provider runs out.
type TokenSet struct {
	AccessToken  string
	RefreshToken string
	IDToken      string
	TokenType    string
	Scopes       []string

	// AccessTokenExpiresAt is when the access token itself expires. Past
	// this point the access token can no longer be used against protected
	// services and must be refreshed (if a refresh token is available).
	AccessTokenExpiresAt time.Time

	// RefreshTokenExpiresAt is when the refresh token (and, for Keycloak,
	// the underlying SSO session it belongs to) stops being usable. Zero
	// means the issuer did not report a lifetime for it.
	RefreshTokenExpiresAt time.Time
}

// Session is a server-side record of a signed-in principal. The browser only
// ever learns Session.ID (as an opaque cookie value); everything else stays
// in SessionStore.
type Session struct {
	// ID is a cryptographically random UUID v4, generated by
	// SessionManager.Create. It carries no structure or meaning of its own.
	ID string

	// Tokens holds the current OIDC credentials for this session. Stored
	// encrypted at rest by SessionStore implementations.
	Tokens TokenSet

	// Claims holds only the identity claims the application actually reads
	// (see SessionManager and its callers), not a verbatim copy of every
	// claim the issuer sent.
	Claims Claims

	// ExpiresAt is the session's absolute, non-extendable ceiling: it is
	// never later than the refresh token's own lifetime (or, lacking that
	// information, a configured default), and never later than any
	// configured absolute session lifetime measured from CreatedAt. See
	// SessionManager.computeExpiresAt for the single place this is decided.
	ExpiresAt time.Time

	CreatedAt time.Time
	UpdatedAt time.Time

	// LastSeenAt is the last time this session authenticated a request.
	// Zero means it has never been used since creation. Used to enforce an
	// optional inactivity timeout.
	LastSeenAt time.Time
}

// SessionStore persists opaque sessions. Deliberately left for the
// consuming application to implement against its own database and
// repository conventions (this package stays agnostic of any specific ORM
// or SQL driver) see the secure package for a ready-made AES-256-GCM
// Encryptor to use when implementing the at-rest encryption Session.Tokens
// requires. Implementations must never log Session.Tokens' contents.
type SessionStore interface {
	// Create persists a new session. s.ID is assumed unique (SessionManager
	// generates it as a random UUID v4).
	Create(ctx context.Context, s *Session) error

	// Get retrieves a session without locking it for update. Used for
	// read-only lookups (the common, non-refreshing request path, and
	// federated logout's need to read the ID token before deleting).
	// Returns an error wrapping ErrSessionNotFound if id does not exist.
	Get(ctx context.Context, id string) (*Session, error)

	// Touch updates only LastSeenAt, without taking a row lock. Used on the
	// common request path where no refresh is needed, so recording activity
	// never costs more than a single-column update.
	Touch(ctx context.Context, id string, lastSeenAt time.Time) error

	// WithLock loads the session identified by id inside an atomic unit of
	// work (e.g. SELECT ... FOR UPDATE inside a transaction), invokes fn
	// with it, and if fn returns a non-nil *Session persists every
	// field of the returned session (tokens, claims, expiry, timestamps)
	// before releasing the lock. If fn returns (nil, nil), the session is
	// left completely unchanged. This is what guarantees at most one
	// concurrent refresh per session: a second request that arrives while
	// the first is refreshing blocks until the first's transaction commits,
	// then observes the already-refreshed state.
	//
	// If fn returns an error, no changes are persisted and the error is
	// returned as-is (wrapped ErrSessionNotFound included) to the caller.
	WithLock(ctx context.Context, id string, fn func(ctx context.Context, s *Session) (*Session, error)) error

	// Delete removes a session. Deleting a session that does not exist is
	// not an error: Delete must be idempotent.
	Delete(ctx context.Context, id string) error

	// DeleteExpired removes every session whose ExpiresAt is at or before
	// now and reports how many rows were removed. Safe to call concurrently
	// from multiple instances: the underlying delete is idempotent.
	DeleteExpired(ctx context.Context, now time.Time) (int64, error)
}
